### PR TITLE
Fix migrations to work with latest MariaDB patch versions

### PR DESCRIPTION
**Pull request by slachiewicz**
see PR #1213

### CODE REVIEW

**Comment by goekay** [comment]
you are rewriting history (i.e. modifying executed migrations). this is always problematic due to existing installations and users of steve. i (we) try to make upgrades between versions seamless.

**Comment by slachiewicz** [comment]
Yes I've made movements only locally to files.
This one where I've dropped and recreated FK are equally to FC existing in version before this file. So this change should be transparent I hope.

If not this way, what other options do we have?

**Comment by juherr** [comment]
@slachiewicz 
 
It is not possible to modify migration files because the checksum of the file is stored and any modification will be considered as corruption and will break the next migrations.

> If not this way, what other options do we have?

See my proposition 
https://github.com/steve-community/steve/pull/1213#issuecomment-1685368887_

**Comment by goekay** [comment]
> It is not possible to modify migration files because the checksum of the file is stored and any modification will be considered as corruption and will break the next migration.

exactly. flyway keeps migration executions in a database table. by the way, there is a way to fix checksums and we used it once: https://github.com/steve-community/steve/wiki/FAQ#how-can-i-upgrade-from-1xx-to-2xx but i am hesitant when it comes to this. it is an annoyance for users and we should use this card really carefully and sparingly.

**Pull request closed without merging**
