### PR TITLE
migration bug fixed  V0_8_6__update.sql

### PR DESCRIPTION
**Pull request by mahmudarslan**

### CODE REVIEW

**Comment by juherr** [comment]
You cannot update migrations that were already released because it will broke servers currently in production: an hash of the migration file is done and store in database, and will fail if a previous migration changed.

**Comment by juherr** [comment]
Related to #1394

**Comment by juherr** [comment]
Should be fixed by #1455

**Comment by goekay** [comment]
what is the state of this PR after merging #1439 ?

**Comment by goekay** [comment]
i am closing this issue due to inactivity. feel free to reopen if it is still relevant.

**Pull request closed without merging**
