### PR TITLE
Add column energy charged in Wh

### PR DESCRIPTION
**Pull request by mosea3**
Treating Feature request issue #738

### CODE REVIEW

**Comment by goekay** [comment]
hey @mosea3 thanks for the contribution!

this PR is missing same cases:
1. stop value will be missing for ongoing transactions. you work does not handle this.
2. there is a detailed transaction page (the view when you click on a transaction). for the sake of completeness, this page should include the energy charged as well.

**Comment by mosea3** [comment]
ok, will do

**Comment by nh38** [comment]
Hi, what's the status here?

**Comment by goekay** [comment]
i am closing this PR since it has been in this unfinished state for a long time.

**Pull request closed without merging**
